name: Build and Deploy to AWS

on:
  push:
    branches: [ latest ]
#  pull_request:
#    branches: [ latest ]

jobs:
  build:
    name: 'Fullstack build'
    runs-on: ubuntu-latest

    environment: sandbox

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache NPM packages
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node_modules-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-${{ matrix.node-version }}-

    - name: Run build
      run: |
        npm install
        npm run build

    - name: Store dist
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  deploy:
    name: 'Deploy to AWS'
    needs: build
    runs-on: ubuntu-latest

    environment: sandbox

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Cache NPM packages
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node_modules-14.x-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-14.x-

      - name: Download dist
        uses: actions/download-artifact@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Cache CDK outputs
        uses: actions/cache@v2
        with:
          path: ./cdk.out
          key: ${{ runner.os }}-cdk-14.x-${{ hashFiles('**/dist', '**/cdk') }}
          restore-keys: |
            ${{ runner.os }}-cdk-14.x-

      - name: CDK Deploy
        run: npx cdk deploy
